title: Alec on Cyber
description: My own notes on how to perform Cyber Security.
# author: Alec on Cyber
# email: none@none.com
github: https://github.com/aleconcyber
about: Alec on Cyber
#disqus_shortname: programming
#google_analytics: UA-1111111-1
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "https://www.facebook.com/"
#    - icon: fa-twitter
#      link: "https://twitter.com/aleconcyber"
#    - icon: fa-linkedin
#      link: "https://www.linkedin.com/in/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/aleconcyber"

#share:
#  twitter_username: tmjam3011
#  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://aleconcyber.github.io/blog_v1"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

theme: jekyll-theme-slate
